<!-- MENU DE NAVEGAÇÃO DO TOPO!-->

<nav class="navbar navbar-default navbar-fixed-top navbar-color">
	<div class="container-fluid">
		<!-- PERMITE A NAVEGAÇÃO EM DISPOSITIVOS MOBILE!-->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="http://localhost/UnetB/index.php"><img src="http://localhost/UnetB/public/images/logo.png" width="40px"></a>
		
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="http://localhost/UnetB/index.php">HOME</a></li>
				<li><a href="http://localhost/UnetB/public/sobre.php">SOBRE</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li><a href="http://localhost/UnetB/public/user_registration.php">CADASTRAR</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">USUÁRIO<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="http://localhost/UnetB/public/loginInterface.php">ENTRAR</a></li>
						<li><a href="#">PERFIL</a></li>
						<li><a href="http://localhost/UnetB/public/netinfo.php">TESTE</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">Separated link</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>

<!--FINAL DO MENU DE NAVEGAÇÃO DO TOPO!-->
