<!-- MENU DE NAVEGAÇÃO DO TOPO!-->

<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<!-- PERMITE A NAVEGAÇÃO EM DISPOSITIVOS MOBILE!-->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="../index.php">UNetB</a>
			<img src="../images/logo.png"/>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="../index.php">HOME</a></li>
				<li><a href="../public/sobre.php">SOBRE</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li><a href="../public/user_registration.php">CADASTRAR</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">USUÁRIO<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="./public/loginInterface.php">Entrar</a></li>
						<li><a href="#">Perfil</a></li>
						<li><a href="./public/netinfo.php">Teste de velocidade</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">Separated link</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>

<!--FINAL DO MENU DE NAVEGAÇÃO DO TOPO!-->
